In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import joblib

In [3]:
df = pd.read_csv("irrigation_prediction.csv")
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  str
 14  Water_Source             10000 non-null  str
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  str
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  str
 19  Irrigation_Need          10000 non-null  str
dtypes: float64(11), str(9)
memory usage: 2.0 MB

In [5]:
df.isnull().sum()

Soil_Type                  0
Soil_pH                    0
Soil_Moisture              0
Organic_Carbon             0
Electrical_Conductivity    0
Temperature_C              0
Humidity                   0
Rainfall_mm                0
Sunlight_Hours             0
Wind_Speed_kmh             0
Crop_Type                  0
Crop_Growth_Stage          0
Season                     0
Irrigation_Type            0
Water_Source               0
Field_Area_hectare         0
Mulching_Used              0
Previous_Irrigation_mm     0
Region                     0
Irrigation_Need            0
dtype: int64

In [9]:
# STEP 7 — Check Target Classes
df['Irrigation_Need'].value_counts()

Irrigation_Need
Low       5864
Medium    3800
High       336
Name: count, dtype: int64

WHY DO WE NEED ENCODER?

Because ML models understand only:

NUMBERS

They do NOT understand text directly.

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Soil_Type'] = encoder.fit_transform(df['Soil_Type'])

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Crop_Type'] = encoder.fit_transform(df['Soil_Type'])

In [12]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Crop_Growth_Stage'] = encoder.fit_transform(df['Soil_Type'])

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Season'] = encoder.fit_transform(df['Soil_Type'])

instead of doing one at a time know encoding all at a time

In [13]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

categorical_columns = [
    'Irrigation_Type',
    'Water_Source',
    'Mulching_Used',
    'Region',
    'Irrigation_Need'
]

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

In [14]:
df.info()  # all succeffully converted from string to number coz ml can only understand number

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  int64
 14  Water_Source             10000 non-null  int64
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  int64
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  int64
 19  Irrigation_Need          10000 non-null  int64
dtypes: float64(11), int64(5), str(4)
memory usage: 1.7 MB

In [12]:
df

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,2,2,4.73,1,1.98,3,1
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,0,0,12.22,1,33.56,0,2
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,1,2,5.52,1,34.62,3,1
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,0,2,1.43,1,84.03,2,2
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,0,3,2.52,0,60.86,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,7.01,26.67,0.86,0.76,27.61,52.20,1075.12,7.41,19.66,Sugarcane,Sowing,Kharif,1,0,2.62,1,92.44,3,1
9996,Clay,5.40,49.44,0.90,1.19,34.03,52.31,1591.84,9.86,5.66,Maize,Sowing,Kharif,2,0,4.87,0,15.46,3,1
9997,Loamy,4.97,60.63,0.99,1.30,36.68,68.16,2384.87,10.75,13.40,Potato,Harvest,Kharif,0,0,10.08,1,116.36,2,1
9998,Loamy,7.12,44.33,1.56,1.08,31.50,64.83,2397.01,4.03,3.05,Sugarcane,Harvest,Kharif,2,2,11.11,1,118.17,1,1
9999,Sandy,5.65,62.25,1.48,3.00,35.71,45.33,177.69,10.93,12.32,Potato,Harvest,Kharif,0,1,11.32,0,98.88,2,2

In [17]:
X = df.drop('Irrigation_Need', axis=1) #droping coz ouput will irrigation_need

y = df['Irrigation_Need']

In [18]:
X

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,2,2,4.73,1,1.98,3
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,0,0,12.22,1,33.56,0
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,1,2,5.52,1,34.62,3
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,0,2,1.43,1,84.03,2
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,0,3,2.52,0,60.86,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,7.01,26.67,0.86,0.76,27.61,52.20,1075.12,7.41,19.66,Sugarcane,Sowing,Kharif,1,0,2.62,1,92.44,3
9996,Clay,5.40,49.44,0.90,1.19,34.03,52.31,1591.84,9.86,5.66,Maize,Sowing,Kharif,2,0,4.87,0,15.46,3
9997,Loamy,4.97,60.63,0.99,1.30,36.68,68.16,2384.87,10.75,13.40,Potato,Harvest,Kharif,0,0,10.08,1,116.36,2
9998,Loamy,7.12,44.33,1.56,1.08,31.50,64.83,2397.01,4.03,3.05,Sugarcane,Harvest,Kharif,2,2,11.11,1,118.17,1
9999,Sandy,5.65,62.25,1.48,3.00,35.71,45.33,177.69,10.93,12.32,Potato,Harvest,Kharif,0,1,11.32,0,98.88,2

In [19]:
print(X.iloc[0])

Soil_Type                        Clay
Soil_pH                          6.14
Soil_Moisture                   36.48
Organic_Carbon                   0.42
Electrical_Conductivity          2.17
Temperature_C                    21.9
Humidity                        31.19
Rainfall_mm                    1167.7
Sunlight_Hours                   4.01
Wind_Speed_kmh                   1.97
Crop_Type                       Wheat
Crop_Growth_Stage          Vegetative
Season                           Rabi
Irrigation_Type                     2
Water_Source                        2
Field_Area_hectare               4.73
Mulching_Used                       1
Previous_Irrigation_mm           1.98
Region                              3
Name: 0, dtype: object

In [20]:
y

0       1
1       2
2       1
3       2
4       2
       ..
9995    1
9996    1
9997    1
9998    1
9999    2
Name: Irrigation_Need, Length: 10000, dtype: int64

after encoding,droping
Then:
train_test_split
RandomForest
fit
predict
accuracy.

In [21]:
# STEP 2 — Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

WHAT IS RANDOM FOREST?

It is:

multiple decision trees combined together

Better than:

single decision tree
more stable
higher accuracy

In [ ]:
# STEP 3 — Import Random Forest
from sklearn.ensemble import RandomForestClassifier
# STEP 4 — Create Model
model = RandomForestClassifier()

VERY IMPORTANT

This is where actual learning happens.

Model learns relationships between:

soil
weather
moisture
irrigation need

In [23]:
# STEP 5 — Train Model
model.fit(X_train, y_train)

RandomForestClassifier()

In [24]:
y_pred = model.predict(X_test)
# Model predicts irrigation class for unseen test data.

In [25]:
# STEP 7 — Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7465

In [26]:
# STEP 8 — Classification Report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.62      0.27      0.38        59
           1       0.80      0.83      0.81      1204
           2       0.66      0.65      0.65       737

    accuracy                           0.75      2000
   macro avg       0.69      0.58      0.62      2000
weighted avg       0.74      0.75      0.74      2000

In [28]:
# STEP 9 — Confusion Matrix (IMPORTANT)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 16   0  43]
 [  0 997 207]
 [ 10 247 480]]

see the data is imbalanced so we need to balance the data and balancing should done before the training and after encoding

we can balance the data with multiple appraoch but using smote

In [30]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

WHAT HAPPENS?

SMOTE creates balanced dataset.

STEP 4 — Check New Class Counts

In [31]:
print(y_resampled.value_counts())

Irrigation_Need
1    5864
2    5864
0    5864
Name: count, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled,
    y_resampled,
    test_size=0.2,
    random_state=42
)

In [33]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [34]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8422847399829497

In [36]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      1160
           1       0.84      0.74      0.79      1210
           2       0.74      0.79      0.77      1149

    accuracy                           0.84      3519
   macro avg       0.84      0.84      0.84      3519
weighted avg       0.84      0.84      0.84      3519

In [1]:
# 1. Save Model
import joblib

joblib.dump(model, "irrigation_recommendation_model.pkl")

NameError: name 'model' is not defined

In [41]:
# 2. Save Encoders

# VERY IMPORTANT.
feature_names = X.columns.tolist()
joblib.dump(feature_names, "feature_names.pkl")
joblib.dump(encoder, "fertilizer_encoder.pkl")

['fertilizer_encoder.pkl']

In [40]:
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,0,0,0,2,2,4.73,1,1.98,3,1
1,3,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,3,3,3,0,0,12.22,1,33.56,0,2
2,2,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,2,2,2,1,2,5.52,1,34.62,3,1
3,0,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,0,0,0,0,2,1.43,1,84.03,2,2
4,0,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,0,0,0,0,3,2.52,0,60.86,3,2

In [1]:
import joblib

loaded_model = joblib.load("irrigation_recommendation_model.pkl")

In [2]:
sample = [[
    0,      # Soil_Type encoded
    6.5,    # Soil_pH
    35,     # Soil_Moisture
    0.8,    # Organic_Content
    1.2,    # Electrical_Conductivity
    32,     # Temperature
    65,     # Humidity
    500,    # Rainfall_mm
    8,      # Sunlight_Hours
    12,     # Wind_Speed
    1,      # Crop_Type encoded
    2,      # Growth Stage
    0,      # Season
    1,      # Irrigation_Type
    0,      # Water_Source
    2.5,    # Field_Area
    1,      # Mulching
    20,     # Previous Irrigation
    3       # Region
]]

In [5]:
prediction = loaded_model.predict(sample)

print(prediction)

[2]

c:\Users\Shaik Fahad Jahangir\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [3]:
import pandas as pd

df = pd.read_csv("irrigation_prediction.csv")

print(df.head())
print(df.columns)

  Soil_Type  Soil_pH  Soil_Moisture  Organic_Carbon  Electrical_Conductivity  \
0      Clay     6.14          36.48            0.42                     2.17
1      Silt     6.41          50.56            0.38                     0.23
2     Sandy     7.71          40.07            1.09                     2.18
3      Clay     5.96          12.75            1.56                     0.40
4      Clay     7.76          18.58            0.95                     2.52

   Temperature_C  Humidity  Rainfall_mm  Sunlight_Hours  Wind_Speed_kmh  \
0          21.90     31.19      1167.70            4.01            1.97
1          36.50     26.01       831.28           10.72           16.82
2          41.83     76.41      1844.45            7.75           19.03
3          37.22     43.32       306.26            8.90           11.44
4          22.38     86.44      1875.63           10.39           11.26

  Crop_Type Crop_Growth_Stage  Season Irrigation_Type Water_Source  \
0     Wheat        Vegetative    Rabi         Rainfed    Reservoir
1     Maize         Flowering    Zaid           Canal  Groundwater
2    Cotton           Harvest    Rabi            Drip    Reservoir
3     Wheat            Sowing  Kharif           Canal    Reservoir
4    Cotton            Sowing    Zaid           Canal        River

   Field_Area_hectare Mulching_Used  Previous_Irrigation_mm   Region  \
0                4.73           Yes                    1.98    South
1               12.22           Yes                   33.56  Central
2                5.52           Yes                   34.62    South
3                1.43           Yes                   84.03    North
4                2.52            No                   60.86    South

  Irrigation_Need
0             Low
1          Medium
2             Low
3          Medium
4          Medium
Index(['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage',
       'Season', 'Irrigation_Type', 'Water_Source', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_mm', 'Region', 'Irrigation_Need'],
      dtype='str')

In [4]:
import joblib

model = joblib.load("irrigation_recommendation_model.pkl")

print(model)

RandomForestClassifier()

In [5]:
print(df["Soil_Type"].unique())
print(df["Crop_Type"].unique())
print(df["Crop_Growth_Stage"].unique())
print(df["Season"].unique())
print(df["Irrigation_Type"].unique())
print(df["Water_Source"].unique())
print(df["Mulching_Used"].unique())
print(df["Region"].unique())
print(df["Irrigation_Need"].unique())

<ArrowStringArray>
['Clay', 'Silt', 'Sandy', 'Loamy']
Length: 4, dtype: str
<ArrowStringArray>
['Wheat', 'Maize', 'Cotton', 'Rice', 'Sugarcane', 'Potato']
Length: 6, dtype: str
<ArrowStringArray>
['Vegetative', 'Flowering', 'Harvest', 'Sowing']
Length: 4, dtype: str
<ArrowStringArray>
['Rabi', 'Zaid', 'Kharif']
Length: 3, dtype: str
<ArrowStringArray>
['Rainfed', 'Canal', 'Drip', 'Sprinkler']
Length: 4, dtype: str
<ArrowStringArray>
['Reservoir', 'Groundwater', 'River', 'Rainwater']
Length: 4, dtype: str
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
<ArrowStringArray>
['South', 'Central', 'North', 'East', 'West']
Length: 5, dtype: str
<ArrowStringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

In [7]:
import joblib

encoder = joblib.load("fertilizer_encoder.pkl")
encoder

LabelEncoder()

In [8]:
import joblib

enc = joblib.load("fertilizer_encoder.pkl")

print(type(enc))

try:
    print(enc.classes_)
except:
    print(enc)

<class 'sklearn.preprocessing._label.LabelEncoder'>
['High' 'Low' 'Medium']

In [9]:
import pandas as pd

df = pd.read_csv("irrigation_prediction.csv")

print(df.iloc[0])

Soil_Type                        Clay
Soil_pH                          6.14
Soil_Moisture                   36.48
Organic_Carbon                   0.42
Electrical_Conductivity          2.17
Temperature_C                    21.9
Humidity                        31.19
Rainfall_mm                    1167.7
Sunlight_Hours                   4.01
Wind_Speed_kmh                   1.97
Crop_Type                       Wheat
Crop_Growth_Stage          Vegetative
Season                           Rabi
Irrigation_Type               Rainfed
Water_Source                Reservoir
Field_Area_hectare               4.73
Mulching_Used                     Yes
Previous_Irrigation_mm           1.98
Region                          South
Irrigation_Need                   Low
Name: 0, dtype: object

In [15]:
print(X.iloc[0])

NameError: name 'X' is not defined

In [20]:
import joblib

model = joblib.load("irrigation_recommendation_model.pkl")

print(model.n_features_in_)

19

In [21]:
sample = [[
    "Clay",
    6.14,
    36.48,
    0.42,
    2.17,
    21.9,
    31.19,
    1167.7,
    4.01,
    1.97,
    "Wheat",
    "Vegetative",
    "Rabi",
    2,
    2,
    4.73,
    1,
    1.98,
    3
]]

print(model.predict(sample))

c:\Users\Shaik Fahad Jahangir\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: could not convert string to float: 'Clay'

In [22]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
print(encoder.fit_transform(df["Soil_Type"]))
print(encoder.classes_)

[0 3 2 ... 1 1 2]
['Clay' 'Loamy' 'Sandy' 'Silt']

In [24]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(df["Crop_Type"])
print(encoder.classes_)

['Cotton' 'Maize' 'Potato' 'Rice' 'Sugarcane' 'Wheat']

In [25]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(df["Crop_Growth_Stage"])
print(encoder.classes_)

['Flowering' 'Harvest' 'Sowing' 'Vegetative']

In [26]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(df["Season"])
print(encoder.classes_)

['Kharif' 'Rabi' 'Zaid']

In [27]:
from sklearn.preprocessing import LabelEncoder

for col in [
    "Soil_Type",
    "Crop_Type",
    "Crop_Growth_Stage",
    "Season"
]:
    le = LabelEncoder()
    le.fit(df[col])

    print(f"\n{col}")
    for i, cls in enumerate(le.classes_):
        print(i, "=", cls)

Soil_Type
0 = Clay
1 = Loamy
2 = Sandy
3 = Silt

Crop_Type
0 = Cotton
1 = Maize
2 = Potato
3 = Rice
4 = Sugarcane
5 = Wheat

Crop_Growth_Stage
0 = Flowering
1 = Harvest
2 = Sowing
3 = Vegetative

Season
0 = Kharif
1 = Rabi
2 = Zaid

In [28]:
from sklearn.preprocessing import LabelEncoder

for col in [
    "Irrigation_Type",
    "Water_Source",
    "Mulching_Used",
    "Region",
    "Irrigation_Need"
]:
    le = LabelEncoder()
    le.fit(df[col])

    print(f"\n{col}")
    for i, cls in enumerate(le.classes_):
        print(i, "=", cls)

Irrigation_Type
0 = 0
1 = 1
2 = 2
3 = 3

Water_Source
0 = 0
1 = 1
2 = 2
3 = 3

Mulching_Used
0 = 0
1 = 1

Region
0 = 0
1 = 1
2 = 2
3 = 3
4 = 4

Irrigation_Need
0 = 0
1 = 1
2 = 2

In [29]:
import pandas as pd

df = pd.read_csv("irrigation_prediction.csv")

print(df[[
    "Irrigation_Type",
    "Water_Source",
    "Mulching_Used",
    "Region"
]].head(20))

   Irrigation_Type Water_Source Mulching_Used   Region
0          Rainfed    Reservoir           Yes    South
1            Canal  Groundwater           Yes  Central
2             Drip    Reservoir           Yes    South
3            Canal    Reservoir           Yes    North
4            Canal        River            No    South
5        Sprinkler  Groundwater           Yes     East
6        Sprinkler    Reservoir            No     West
7          Rainfed    Reservoir           Yes     West
8        Sprinkler    Rainwater           Yes  Central
9          Rainfed    Reservoir           Yes  Central
10           Canal        River            No    North
11       Sprinkler    Reservoir           Yes     East
12       Sprinkler    Reservoir            No    North
13           Canal        River           Yes     East
14           Canal    Rainwater            No    North
15         Rainfed  Groundwater            No     West
16       Sprinkler    Rainwater            No     West
17           Canal    Reservoir            No    South
18         Rainfed    Rainwater            No     East
19           Canal    Reservoir            No    South